number1 = int(input("Give me number 1: "))
number2 = int(input("Give me number 2: "))

print("Min:", number1 - number2)
print("Plus:", number1 + number2)
print("Multiply:", number1 * number2)
print("Division:", number1 / number2)
print("Modulus:", number1 % number2)
print("Afronden:", number1 // number2)
print("Mcht:", number1 ** number2)